// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIK4ZUQvzPk09VRrQscXzBGY73ruBeEnA',
    appId: '1:985191148054:web:c82263d8beefd745e56337',
    messagingSenderId: '985191148054',
    projectId: 'eduverse-6aa1d',
    authDomain: 'eduverse-6aa1d.firebaseapp.com',
    storageBucket: 'eduverse-6aa1d.firebasestorage.app',
    measurementId: 'G-2Y83MW53Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZK4Z742-b2G3g3hMGxAE8uvGkwGkmkg',
    appId: '1:985191148054:android:67af83bb2144ccdee56337',
    messagingSenderId: '985191148054',
    projectId: 'eduverse-6aa1d',
    storageBucket: 'eduverse-6aa1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5OICGKwxsjvBvRWePDJJ-eTKk7fRwmoQ',
    appId: '1:985191148054:ios:9ea428772ebf73f7e56337',
    messagingSenderId: '985191148054',
    projectId: 'eduverse-6aa1d',
    storageBucket: 'eduverse-6aa1d.firebasestorage.app',
    iosBundleId: 'com.example.eduverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5OICGKwxsjvBvRWePDJJ-eTKk7fRwmoQ',
    appId: '1:985191148054:ios:9ea428772ebf73f7e56337',
    messagingSenderId: '985191148054',
    projectId: 'eduverse-6aa1d',
    storageBucket: 'eduverse-6aa1d.firebasestorage.app',
    iosBundleId: 'com.example.eduverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIK4ZUQvzPk09VRrQscXzBGY73ruBeEnA',
    appId: '1:985191148054:web:4b02803047ef32e9e56337',
    messagingSenderId: '985191148054',
    projectId: 'eduverse-6aa1d',
    authDomain: 'eduverse-6aa1d.firebaseapp.com',
    storageBucket: 'eduverse-6aa1d.firebasestorage.app',
    measurementId: 'G-LP1P8XTX37',
  );
}
