// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/// IMPORTANT: YOU MUST UPDATE THE VALUES BELOW WITH YOUR ACTUAL FIREBASE PROJECT CONFIGURATION.
/// RUN `flutterfire configure` OR MANUALLY COPY VALUES FROM YOUR FIREBASE CONSOLE.
/// THE APP WILL FAIL TO INITIALIZE IF THESE PLACEHOLDERS ARE LEFT UNCHANGED.
/// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'UPDATE-THIS-API-KEY',
    appId: '1:1234567890:web:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'eduverse-project-id',
    authDomain: 'eduverse-project-id.firebaseapp.com',
    storageBucket: 'eduverse-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'UPDATE-THIS-API-KEY',
    appId: '1:1234567890:android:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'eduverse-project-id',
    storageBucket: 'eduverse-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'UPDATE-THIS-API-KEY',
    appId: '1:1234567890:ios:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'eduverse-project-id',
    storageBucket: 'eduverse-project-id.appspot.com',
    iosClientId: '1234567890-abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.eduverse.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'UPDATE-THIS-API-KEY',
    appId: '1:1234567890:ios:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'eduverse-project-id',
    storageBucket: 'eduverse-project-id.appspot.com',
    iosClientId: '1234567890-abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.eduverse.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'UPDATE-THIS-API-KEY',
    appId: '1:1234567890:web:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'eduverse-project-id',
    authDomain: 'eduverse-project-id.firebaseapp.com',
    storageBucket: 'eduverse-project-id.appspot.com',
  );
}
