// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCYmb1VpP3DqVsPDwr0rMP0dzniv_7yA',
    appId: '1:465308079104:web:0258746f5c01c3948cb4e5',
    messagingSenderId: '465308079104',
    projectId: 'eduverse-dad5e',
    authDomain: 'eduverse-dad5e.firebaseapp.com',
    storageBucket: 'eduverse-dad5e.firebasestorage.app',
    measurementId: 'G-7XM3WMBM7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mLEiMU76w_U7QnIC7yOmR316tsoeEs4',
    appId: '1:465308079104:android:3f59ce57c51d2b118cb4e5',
    messagingSenderId: '465308079104',
    projectId: 'eduverse-dad5e',
    storageBucket: 'eduverse-dad5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUPNJ5AkQynKUPDu8xzKXweiNhHxHKi4U',
    appId: '1:465308079104:ios:c35d1b6752455b0a8cb4e5',
    messagingSenderId: '465308079104',
    projectId: 'eduverse-dad5e',
    storageBucket: 'eduverse-dad5e.firebasestorage.app',
    iosBundleId: 'com.eduverse.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5OICGKwxsjvBvRWePDJJ-eTKk7fRwmoQ',
    appId: '1:985191148054:ios:9ea428772ebf73f7e56337',
    messagingSenderId: '985191148054',
    projectId: 'eduverse-6aa1d',
    storageBucket: 'eduverse-6aa1d.firebasestorage.app',
    iosBundleId: 'com.eduverse.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIK4ZUQvzPk09VRrQscXzBGY73ruBeEnA',
    appId: '1:985191148054:web:4b02803047ef32e9e56337',
    messagingSenderId: '985191148054',
    projectId: 'eduverse-6aa1d',
    authDomain: 'eduverse-6aa1d.firebaseapp.com',
    storageBucket: 'eduverse-6aa1d.firebasestorage.app',
    measurementId: 'G-LP1P8XTX37',
  );
}